### ISSUE TITLE
IE7/8 Invalid property value

### ISSUE THREAD

**Issue by Integralist** [ded/morpheus#7]
Here we go again :)

Both IE7 & 8 (in Standards mode vs Mac OSX Parallels Desktop) are showing the error...

SCRIPT380: Invalid property value.
morpheus.js, line 171 character 13

```
(els[i].style[camelize(k)] = v);
```

**Comment by ded** [comment]
ummm... really? I'll have to cruise thru last day of commits to see what broke that

**Comment by ded** [comment]
i'm on master and not getting this error. could you double check you have the latest and perhaps jot down what code you're trying to execute.

**Comment by ded** [comment]
fixed in 0.1.8

**Comment by Integralist** [comment]
This issue is still appearing for me.

I've pulled the lastest version and my test page can be seen here:
http://codepaste.net/p9dr6k

I've also uploaded a screen shot of what IE7/8 looks like:
http://cl.ly/2p311O3E3K3C0K0F0F0Q

Maybe it's something in my example that's wrong? (i'm not interested in using Ender hence why I removed it's code and just used basic getElementById/TagName methods instead).

M.

**Comment by ded** [comment]
i see the issue in your code. read the _usage notes_ on the [README](https://github.com/ded/morpheus/blob/master/README.md)

you can't morph colors like 'orange' — they need to be represented as hex, or RGB. I verified that your example will work if replaced with a hex.

I will however see what I can do when such thing arrises.
